// <auto-generated />
using LaTiendaIS.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaTiendaIS.Shared.Migrations
{
    [DbContext(typeof(DBLaTiendaContext))]
    [Migration("20240123185108_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaTiendaIS.Shared.Models.Articulo", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("IVA")
                        .HasColumnType("real");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdColor")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdTalle")
                        .HasColumnType("int");

                    b.Property<float>("MargenDeGanacia")
                        .HasColumnType("real");

                    b.Property<float>("NetoGravado")
                        .HasColumnType("real");

                    b.Property<double>("PrecioDeVenta")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdColor");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdTalle");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("LaTiendaIS.Shared.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("LaTiendaIS.Shared.Models.ColorArticulo", b =>
                {
                    b.Property<int>("IdColor")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdColor");

                    b.ToTable("ColorArticulo");
                });

            modelBuilder.Entity("LaTiendaIS.Shared.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("LaTiendaIS.Shared.Models.Talle", b =>
                {
                    b.Property<int>("IdTalle")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionTalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTalle");

                    b.ToTable("Talle");
                });

            modelBuilder.Entity("LaTiendaIS.Shared.Models.Articulo", b =>
                {
                    b.HasOne("LaTiendaIS.Shared.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaTiendaIS.Shared.Models.ColorArticulo", "Color")
                        .WithMany()
                        .HasForeignKey("IdColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaTiendaIS.Shared.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaTiendaIS.Shared.Models.Talle", "Talle")
                        .WithMany()
                        .HasForeignKey("IdTalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Color");

                    b.Navigation("Marca");

                    b.Navigation("Talle");
                });
#pragma warning restore 612, 618
        }
    }
}
